version: "2"
services:
  moonbot:
    container_name: moonbot 
    image: "moonbot"
    build:
      context: bot
      dockerfile: Dockerfile
    restart: unless-stopped

  myfxbook_script1:
    container_name: myfxbook_script1
    image: "myfxbook_script1"
    build:
      context: bot
      dockerfile: myfxbook_script.Dockerfile